version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: order_postgres
    restart: always
    environment:
      POSTGRES_USER: sibs_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order_db

    ports:

      - "5432:5432"

    volumes:
      - sibs_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  sibs_data: